### ISSUE TITLE
docker image multi-platform support

### ISSUE THREAD

**Issue by leo-the-nardo** [Leoff00/ta-pago-bot#10]
actually the docker image can't run on arm based architetures
![image](https://github.com/Leoff00/ta-pago-bot/assets/123664357/dc5255bd-feeb-4935-9cfb-42f95331b598)

**Comment by Leoff00** [comment]
soon will be resolved, thanks for the report

**Comment by leo-the-nardo** [comment]
Solved on https://github.com/Leoff00/ta-pago-bot/pull/14
