### ISSUE TITLE
mods can't edit existent score 

### ISSUE THREAD

**Issue by leo-the-nardo** [Leoff00/ta-pago-bot#2]
Actually, If you need to edit a user's score, you should manually edit the database field, but, currently the db is stuck in the container which is inaccessible (no sh, no bash)

**Workaround:**
Read a fixed but empty path. and leave the responsibility of whoever deploys this to bind the external path of the db with the internal path expected by the application
Probably removing line 6 at [dockerfile](https://github.com/Leoff00/ta-pago-bot/blob/main/dockerfile) fixes it.
**Suggestion**
However, the ideal world is that _moderators_ could edit a specific score through the bot itself, instead of directly editing the database.

**Comment by Leoff00** [comment]
At this moment mods can really restart the workout counter, **see in the #33**.

**Workaround**
The suggestion to let whoever deploys the app deals with the db path is good, but at the moment, this is the best way to wipe out him.

About your suggestion, i enjoy a lot this idea, i can implement this feature soon. Anyway i'll let this issue open and close her when i finish these topics.

**Comment by Leoff00** [comment]
At this moment mods can really restart the workout counter, see in the [#33](https://github.com/Leoff00/ta-pago-bot/commit/b66e3828e25000af43811903cccaf39d929c8559).

**Workaround**
The suggestion to let whoever deploys the app deals with the db path is good, but at the moment, this is the best way to wipe out him.

About your suggestion, i enjoy a lot this idea, i can implement this feature soon. Anyway i'll let this issue open and close her when i finish these topics.

**Comment by Leoff00** [comment]
Closing this issue rn, the feature is already gracefully implemented. See more in the PR #9
